### ISSUE TITLE
error: Please specify inital embedding weights

### ISSUE THREAD

**Issue by HuYaa** [ericholgate/vulgartwitter#1]
Hi,
I am trying to run the bilstm.py, and I have the error "Please specify inital embedding weights". I don't know how to deal with that and don't know how to embedding weights. I will be very grateful if I receive your reply.

**Comment by ericholgate** [comment]
Hi HuYaa,

The model requires initial embedding weights to be passed as input. We use 200 dimensional CBOW embeddings tuned on tweets from prior work (I've included the full citation at the end of this post). You can find the download link here: https://www.l2f.inesc-id.pt/~wlin/public/embeddings/ .

Embedding citation:
Ramon Astudillo, Silvio Amir, Wang Ling, Mario Silva, and Isabel Trancoso. 2015. Learning word representations from scarce and noisy data with embedding subspaces. In Proceedings of the 53rd Annual Meeting of the Association for Computational Linguistics and the 7th International Joint Conference on Natural Language Processing, pages 1074–1084.

**Comment by HuYaa** [comment]
Thank you very much!!!
